name: WordGolf
options:
  bundleIdPrefix: com.palefire
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  createIntermediateGroups: true

packages:
  WordGolfCore:
    path: Packages/WordGolfCore

targets:
  # macOS App
  WordGolf:
    type: application
    platform: macOS
    sources:
      - path: WordGolfProject/WordGolf
        excludes:
          - "*.app"
          - "*.app/**"
          - WordGolf
          - GameModel.swift  # Now in WordGolfCore package
    dependencies:
      - package: WordGolfCore
    info:
      path: WordGolfProject/WordGolf/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Word Golf
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: APPL
        CFBundleIconFile: AppIcon
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSApplicationCategoryType: public.app-category.games
        NSHumanReadableCopyright: Released into the public domain by John Bergmayer
    entitlements:
      path: WordGolfProject/WordGolf/WordGolf.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.palefire.WordGolf
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: WordGolfProject/WordGolf/Info.plist
        CODE_SIGN_ENTITLEMENTS: WordGolfProject/WordGolf/WordGolf.entitlements
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"

  # iOS App
  WordGolf-iOS:
    type: application
    platform: iOS
    sources:
      - path: WordGolfProject/WordGolf-iOS
    dependencies:
      - package: WordGolfCore
    info:
      path: WordGolfProject/WordGolf-iOS/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Word Golf
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: APPL
        UILaunchScreen: {}
        NSHumanReadableCopyright: Released into the public domain by John Bergmayer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.palefire.WordGolf-iOS
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: WordGolfProject/WordGolf-iOS/Info.plist
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
